// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AddUserToGroupRequest struct {
	// The email address that the user has associated with their user profile.
	Email *string `json:"email,omitempty"`
	// The group role that you would like to assign this new user to. Supported group roles: ‘Destination Administrator‘, ‘Destination Reviewer‘, ‘Destination Analyst‘, ‘Connector Creator‘, or a custom destination role
	Role *string `json:"role,omitempty"`
}
