// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ColumnUpdateRequest struct {
	// The boolean value specifying whether the sync for the table into the destination is enabled.
	Enabled *bool `json:"enabled,omitempty"`
	// The boolean value specifying whether a column should be hashed
	Hashed *bool `json:"hashed,omitempty"`
}
