// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConnectCardConfigRequest struct {
	ConnectCardConfig *ConnectCardConfig `json:"connect_card_config,omitempty"`
}
