// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MembershipRequest struct {
	// The unique identifier for the user within the Fivetran system.
	ID string `json:"id"`
	// The role that you would like to assign to the user
	Role string `json:"role"`
}
