// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NewDbtProjectRequest struct {
	// The version of dbt that should run the project.
	DbtVersion *string `json:"dbt_version,omitempty"`
	// Default schema in destination.
	DefaultSchema *string `json:"default_schema,omitempty"`
	// Folder in Git repo.
	FolderPath *string `json:"folder_path,omitempty"`
	// Git branch.
	GitBranch *string `json:"git_branch,omitempty"`
	// Git remote url.
	GitRemoteURL *string `json:"git_remote_url,omitempty"`
	// The unique identifier for the Group within the Fivetran system.
	GroupID *string `json:"group_id,omitempty"`
	// Target name to set or override the value from the deployment.yaml.
	TargetName *string `json:"target_name,omitempty"`
	// The number of threads dbt will use.
	Threads *int `json:"threads,omitempty"`
}
