// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NewGroupRequest struct {
	// The name of the group within your account.
	Name *string `json:"name,omitempty"`
}
