// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NewTransformationRequest struct {
	// The unique identifier for the DBT Model within the Fivetran system.
	DbtModelID *string `json:"dbt_model_id,omitempty"`
	// The field indicates whether the tests has been confugured for DBT Transformation.
	RunTests *bool                   `json:"run_tests,omitempty"`
	Schedule *TransformationSchedule `json:"schedule,omitempty"`
}
