// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ReloadStandardConfigRequest struct {
	// Specifies whether all schemas and tables will be enabled or disabled in the standard config
	ExcludeMode *string `json:"exclude_mode,omitempty"`
}
