// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SchemaUpdateRequest struct {
	// The boolean value specifying whether the sync for the table into the destination is enabled.
	Enabled *bool `json:"enabled,omitempty"`
	// The set of tables within your database schema config that are synced into the destination
	Tables map[string]TableUpdateRequest `json:"tables,omitempty"`
}
