// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TeamMembershipRequest struct {
	// The user's role within the team
	Role *string `json:"role,omitempty"`
	// The unique identifier of user
	UserID *string `json:"user_id,omitempty"`
}
