// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TeamRequest struct {
	// The description of the team within your account
	Description *string `json:"description,omitempty"`
	// The name of the team within your account
	Name *string `json:"name,omitempty"`
	// The account role of the team
	Role *string `json:"role,omitempty"`
}
