// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TrustCertificateRequest struct {
	// The unique identifier for the connector
	ConnectorID *string `json:"connector_id,omitempty"`
	// The unique identifier for the destination.
	DestinationID *string `json:"destination_id,omitempty"`
	// The certificate encoded in base64.
	EncodedCert string `json:"encoded_cert"`
	// Hash of the certificate.
	Hash string `json:"hash"`
}
