// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type UpdateTransformationRequest struct {
	// The field indicates whether the tests has been confugured for DBT Transformation.
	RunTests *bool                   `json:"run_tests,omitempty"`
	Schedule *TransformationSchedule `json:"schedule,omitempty"`
}
