// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type UpdateUserRequest struct {
	// The last name of the user.
	FamilyName string `json:"family_name"`
	// The first name of the user.
	GivenName string `json:"given_name"`
	// The phone number of the user.
	Phone *string `json:"phone,omitempty"`
	// The user's avatar as a URL link (for example, 'http://mycompany.com/avatars/john_white.png') or base64 data URI (for example, 'data:image/png;base64,aHR0cDovL215Y29tcGFueS5jb20vYXZhdGFycy9qb2huX3doaXRlLnBuZw==')
	Picture *string `json:"picture,omitempty"`
	// The role that you would like to assign to the user
	Role *string `json:"role,omitempty"`
}
