// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type UpdateMembershipRequest struct {
	// The role that you would like to assign to the user
	Role string `json:"role"`
}
