// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type WebhookRequest struct {
	// Boolean, if set to true, webhooks are immediately sent in response to events
	Active *bool `json:"active,omitempty"`
	// The array of event types
	Events []string `json:"events,omitempty"`
	// The secret string used for payload signing. Optional.
	Secret *string `json:"secret,omitempty"`
	// Your webhooks URL endpoint for your application
	URL *string `json:"url,omitempty"`
}
