// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"encoding/json"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"terraform/internal/sdk/pkg/models/shared"
)

func (r *DestinationResourceModel) ToSDKType() *shared.DestinationRequest {
	groupID := r.GroupID.ValueString()
	region := new(shared.DestinationRequestRegionEnum)
	if !r.Region.IsUnknown() && !r.Region.IsNull() {
		*region = shared.DestinationRequestRegionEnum(r.Region.ValueString())
	} else {
		region = nil
	}
	service := r.Service.ValueString()
	timeZoneOffset := r.TimeZoneOffset.ValueString()
	out := shared.DestinationRequest{
		GroupID:        groupID,
		Region:         region,
		Service:        service,
		TimeZoneOffset: timeZoneOffset,
	}
	return &out

}

func (r *DestinationResourceModel) RefreshFromSDKType(resp *shared.DestinationResponse) {
	if resp.GroupID != nil {
		r.GroupID = types.StringValue(*resp.GroupID)
	} else {
		r.GroupID = types.StringNull()
	}
	if resp.ID != nil {
		r.ID = types.StringValue(*resp.ID)
	} else {
		r.ID = types.StringNull()
	}
	if resp.Region != nil {
		r.Region = types.StringValue(string(*resp.Region))
	} else {
		r.Region = types.StringNull()
	}
	if resp.Service != nil {
		r.Service = types.StringValue(*resp.Service)
	} else {
		r.Service = types.StringNull()
	}
	if resp.SetupStatus != nil {
		r.SetupStatus = types.StringValue(*resp.SetupStatus)
	} else {
		r.SetupStatus = types.StringNull()
	}
	r.SetupTests = nil
	for _, setupTestsItem := range resp.SetupTests {
		var setupTests1 SetupTestResultResponse
		setupTests1.Details = make(map[string]types.String)
		for key, value := range setupTestsItem.Details {
			result, _ := json.Marshal(value)
			setupTests1.Details[key] = types.StringValue(string(result))
		}
		if setupTestsItem.Message != nil {
			setupTests1.Message = types.StringValue(*setupTestsItem.Message)
		} else {
			setupTests1.Message = types.StringNull()
		}
		if setupTestsItem.Status != nil {
			setupTests1.Status = types.StringValue(*setupTestsItem.Status)
		} else {
			setupTests1.Status = types.StringNull()
		}
		if setupTestsItem.Title != nil {
			setupTests1.Title = types.StringValue(*setupTestsItem.Title)
		} else {
			setupTests1.Title = types.StringNull()
		}
		r.SetupTests = append(r.SetupTests, setupTests1)
	}
	if resp.TimeZoneOffset != nil {
		r.TimeZoneOffset = types.StringValue(*resp.TimeZoneOffset)
	} else {
		r.TimeZoneOffset = types.StringNull()
	}

}
