// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type AddUserToTeamRequest struct {
	Accept                *string                       `header:"style=simple,explode=false,name=Accept"`
	TeamMembershipRequest *shared.TeamMembershipRequest `request:"mediaType=application/json"`
	// The unique identifier for the team within the account
	TeamID string `pathParam:"style=simple,explode=false,name=teamId"`
}

type AddUserToTeamResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	AddUserToTeam201ApplicationJSONAny interface{}
}
