// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type AddUserMembershipInConnectorRequest struct {
	Accept            *string                   `header:"style=simple,explode=false,name=Accept"`
	MembershipRequest *shared.MembershipRequest `request:"mediaType=application/json"`
	// The unique identifier for the user within the account.
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
}

type AddUserMembershipInConnectorResponse struct {
	ContentType string
	// Successful response
	MembershipResponse *shared.MembershipResponse
	StatusCode         int
	RawResponse        *http.Response
}
