// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type ApproveCertificateRequest struct {
	Accept                  *string                         `header:"style=simple,explode=false,name=Accept"`
	TrustCertificateRequest *shared.TrustCertificateRequest `request:"mediaType=application/json"`
}

type ApproveCertificateResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	ApproveCertificate200ApplicationJSONAny interface{}
}
