// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type ApproveFingerprintRequest struct {
	Accept                  *string                         `header:"style=simple,explode=false,name=Accept"`
	TrustFingerprintRequest *shared.TrustFingerprintRequest `request:"mediaType=application/json"`
}

type ApproveFingerprintResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	ApproveFingerprint200ApplicationJSONAny interface{}
}
