// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ConnectorColumnConfigRequest struct {
	Accept *string `header:"style=simple,explode=false,name=Accept"`
	// The unique identifier for the connector within the Fivetran system
	ConnectorID string `pathParam:"style=simple,explode=false,name=connectorId"`
	// The database schema name within your destination
	Schema string `pathParam:"style=simple,explode=false,name=schema"`
	// The table name within your database schema
	Table string `pathParam:"style=simple,explode=false,name=table"`
}

type ConnectorColumnConfigResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	ConnectorColumnConfig200ApplicationJSONAny interface{}
}
