// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type CreateGroupWebhookRequest struct {
	Accept         *string                `header:"style=simple,explode=false,name=Accept"`
	WebhookRequest *shared.WebhookRequest `request:"mediaType=application/json"`
	// The group ID
	GroupID string `pathParam:"style=simple,explode=false,name=groupId"`
}

type CreateGroupWebhookResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	CreateGroupWebhook200ApplicationJSONAny interface{}
}
