// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type CreateDbtTransformationRequest struct {
	Accept                   *string                          `header:"style=simple,explode=false,name=Accept"`
	NewTransformationRequest *shared.NewTransformationRequest `request:"mediaType=application/json"`
	// The unique identifier for the DBT Project within the Fivetran system.
	ProjectID string `pathParam:"style=simple,explode=false,name=projectId"`
}

type CreateDbtTransformationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	CreateDbtTransformation201ApplicationJSONAny interface{}
}
