// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type CreateConnectorRequest struct {
	Accept                *string                       `header:"style=simple,explode=false,name=Accept"`
	NewConnectorRequestV1 *shared.NewConnectorRequestV1 `request:"mediaType=application/json"`
}

type CreateConnectorResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	CreateConnector201ApplicationJSONAny interface{}
}
