// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type CreateGroupRequest struct {
	Accept          *string                 `header:"style=simple,explode=false,name=Accept"`
	NewGroupRequest *shared.NewGroupRequest `request:"mediaType=application/json"`
}

type CreateGroupResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	CreateGroup201ApplicationJSONAny interface{}
}
