// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type CreateUserRequest struct {
	Accept         *string                `header:"style=simple,explode=false,name=Accept"`
	NewUserRequest *shared.NewUserRequest `request:"mediaType=application/json"`
}

type CreateUserResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	CreateUser201ApplicationJSONAny interface{}
}
