// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type CreateDbtProjectRequest struct {
	Accept               *string                      `header:"style=simple,explode=false,name=Accept"`
	NewDbtProjectRequest *shared.NewDbtProjectRequest `request:"mediaType=application/json"`
}

type CreateDbtProjectResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	CreateDbtProject201ApplicationJSONAny interface{}
}
