// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteDbtTransformationRequest struct {
	Accept *string `header:"style=simple,explode=false,name=Accept"`
	// The unique identifier for the DBT Transformation within the Fivetran system.
	TransformationID string `pathParam:"style=simple,explode=false,name=transformationId"`
}

type DeleteDbtTransformationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	DeleteDbtTransformation200ApplicationJSONAny interface{}
}
