// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteUserFromTeamRequest struct {
	Accept *string `header:"style=simple,explode=false,name=Accept"`
	// The unique identifier for the team within the account
	TeamID string `pathParam:"style=simple,explode=false,name=teamId"`
	// The unique identifier for the user within the account
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
}

type DeleteUserFromTeamResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	DeleteUserFromTeam200ApplicationJSONAny interface{}
}
