// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteWebhookRequest struct {
	Accept *string `header:"style=simple,explode=false,name=Accept"`
	// The webhook ID
	WebhookID string `pathParam:"style=simple,explode=false,name=webhookId"`
}

type DeleteWebhookResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	DeleteWebhook204ApplicationJSONAny interface{}
}
