// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type DestinationDetailsRequest struct {
	Accept *string `header:"style=simple,explode=false,name=Accept"`
	// The unique identifier for the destination within your Fivetran account.
	DestinationID string `pathParam:"style=simple,explode=false,name=destinationId"`
}

// DestinationDetails200ApplicationJSON - Successful response
type DestinationDetails200ApplicationJSON struct {
	// Response status code
	Code *string                     `json:"code,omitempty"`
	Data *shared.DestinationResponse `json:"data,omitempty"`
	// Response status text
	Message *string `json:"message,omitempty"`
}

type DestinationDetailsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	DestinationDetails200ApplicationJSONObject *DestinationDetails200ApplicationJSON
}
