// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type MetadataConnectorConfigRequest struct {
	Accept *string `header:"style=simple,explode=false,name=Accept"`
	// The connector name within the Fivetran system
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// [The connector type](https://fivetran.com/docs/rest-api/getting-started#commonterms) identifier within the Fivetran system
	Service string `pathParam:"style=simple,explode=false,name=service"`
}

type MetadataConnectorConfigResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	MetadataConnectorConfig200ApplicationJSONAny interface{}
}
