// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type MetadataConnectorsRequest struct {
	Accept *string `header:"style=simple,explode=false,name=Accept"`
	// The paging cursor. Read more about [pagination in our documentation](https://fivetran.com/docs/rest-api/pagination)
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// The number of records to fetch per page, accepts a number in the range 1..1000. The default value is 100
	Limit *int `queryParam:"style=form,explode=true,name=limit"`
	// The name of the metadata to retrieve
	Name string `pathParam:"style=simple,explode=false,name=name"`
}

type MetadataConnectorsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	MetadataConnectors200ApplicationJSONAny interface{}
}
