// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type ModifyConnectorColumnConfigRequest struct {
	Accept              *string                     `header:"style=simple,explode=false,name=Accept"`
	ColumnUpdateRequest *shared.ColumnUpdateRequest `request:"mediaType=application/json"`
	// The column name within your table
	ColumnName string `pathParam:"style=simple,explode=false,name=columnName"`
	// The unique identifier for the connector within the Fivetran system
	ConnectorID string `pathParam:"style=simple,explode=false,name=connectorId"`
	// The database schema name within your destination (different from the connector schema)
	SchemaName string `pathParam:"style=simple,explode=false,name=schemaName"`
	// The table name within your database schema
	TableName string `pathParam:"style=simple,explode=false,name=tableName"`
}

type ModifyConnectorColumnConfigResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	ModifyConnectorColumnConfig200ApplicationJSONAny interface{}
}
