// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type ModifyDestinationRequest struct {
	DestinationRequest *shared.DestinationRequest `request:"mediaType=application/json"`
	// The unique identifier for the destination within your Fivetran account.
	DestinationID string `pathParam:"style=simple,explode=false,name=destinationId"`
}

type ModifyDestinationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	ModifyDestination200ApplicationJSONAny interface{}
}
