// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type ModifyWebhookRequest struct {
	Accept         *string                `header:"style=simple,explode=false,name=Accept"`
	WebhookRequest *shared.WebhookRequest `request:"mediaType=application/json"`
	// The webhook ID
	WebhookID string `pathParam:"style=simple,explode=false,name=webhookId"`
}

type ModifyWebhookResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	ModifyWebhook200ApplicationJSONAny interface{}
}
