// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type ModifyDbtTransformationRequest struct {
	Accept                      *string                             `header:"style=simple,explode=false,name=Accept"`
	UpdateTransformationRequest *shared.UpdateTransformationRequest `request:"mediaType=application/json"`
	// The unique identifier for the DBT Transformation within the Fivetran system.
	TransformationID string `pathParam:"style=simple,explode=false,name=transformationId"`
}

type ModifyDbtTransformationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	ModifyDbtTransformation200ApplicationJSONAny interface{}
}
