// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ResyncTablesRequest struct {
	Accept      *string             `header:"style=simple,explode=false,name=Accept"`
	RequestBody map[string][]string `request:"mediaType=application/json"`
	// The unique identifier for the connector within the Fivetran system
	ConnectorID string `pathParam:"style=simple,explode=false,name=connectorId"`
}

type ResyncTablesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	ResyncTables200ApplicationJSONAny interface{}
}
