// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type RunDestinationSetupTestsRequest struct {
	Accept               *string                      `header:"style=simple,explode=false,name=Accept"`
	RunSetupTestsRequest *shared.RunSetupTestsRequest `request:"mediaType=application/json"`
	// The unique identifier for the destination within your Fivetran account.
	DestinationID string `pathParam:"style=simple,explode=false,name=destinationId"`
}

type RunDestinationSetupTestsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	RunDestinationSetupTests200ApplicationJSONAny interface{}
}
