// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type TestWebhookRequest struct {
	Accept             *string                    `header:"style=simple,explode=false,name=Accept"`
	WebhookTestRequest *shared.WebhookTestRequest `request:"mediaType=application/json"`
	// The webhook ID
	WebhookID string `pathParam:"style=simple,explode=false,name=webhookId"`
}

type TestWebhookResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	TestWebhook200ApplicationJSONAny interface{}
}
