// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type UpdateTeamMembershipInConnectorRequest struct {
	Accept                  *string                         `header:"style=simple,explode=false,name=Accept"`
	UpdateMembershipRequest *shared.UpdateMembershipRequest `request:"mediaType=application/json"`
	// The unique identifier for the connector within the account
	ConnectorID string `pathParam:"style=simple,explode=false,name=connectorId"`
	// The unique identifier for the team within the account
	TeamID string `pathParam:"style=simple,explode=false,name=teamId"`
}

type UpdateTeamMembershipInConnectorResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	UpdateTeamMembershipInConnector200ApplicationJSONAny interface{}
}
