// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type UpdateUserMembershipInGroupRequest struct {
	Accept                  *string                         `header:"style=simple,explode=false,name=Accept"`
	UpdateMembershipRequest *shared.UpdateMembershipRequest `request:"mediaType=application/json"`
	// The unique identifier for the group within the account.
	GroupID string `pathParam:"style=simple,explode=false,name=groupId"`
	// The unique identifier for the user within the account.
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
}

type UpdateUserMembershipInGroupResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	UpdateUserMembershipInGroup200ApplicationJSONAny interface{}
}
