// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type UpdateUserMembershipRequest struct {
	Accept                  *string                         `header:"style=simple,explode=false,name=Accept"`
	UpdateMembershipRequest *shared.UpdateMembershipRequest `request:"mediaType=application/json"`
	// The unique identifier for the team within the account
	TeamID string `pathParam:"style=simple,explode=false,name=teamId"`
	// The unique identifier for the user within the account
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
}

type UpdateUserMembershipResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	UpdateUserMembership200ApplicationJSONAny interface{}
}
