// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"terraform/internal/sdk/pkg/models/shared"
)

type UpdateTeamMembershipInGroupRequest struct {
	Accept                  *string                         `header:"style=simple,explode=false,name=Accept"`
	UpdateMembershipRequest *shared.UpdateMembershipRequest `request:"mediaType=application/json"`
	// The unique identifier for the group within the account
	GroupID string `pathParam:"style=simple,explode=false,name=groupId"`
	// The unique identifier for the team within the account
	TeamID string `pathParam:"style=simple,explode=false,name=teamId"`
}

type UpdateTeamMembershipInGroupResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	UpdateTeamMembershipInGroup200ApplicationJSONAny interface{}
}
