// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type WebhookDetailsRequest struct {
	Accept *string `header:"style=simple,explode=false,name=Accept"`
	// The webhook ID
	WebhookID string `pathParam:"style=simple,explode=false,name=webhookId"`
}

type WebhookDetailsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	WebhookDetails200ApplicationJSONAny interface{}
}
